### ISSUE TITLE
[18RoyalGorge] unknown keyword :closed_when_used_up

### ISSUE THREAD

**Issue by tphon** [tobymao/18xx#10695]
**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment]
@tphon  We need more information to be able to understand what is happening. What is the ID number (or URL) of the game you are playing? What is the error message you receive? And what are you trying to do when this error occurs?

**Comment by BellmakerSA** [comment]
@ollybh https://18xx.games/game/161776?action=190 the issue appears to be related to the Treaty of Boston event that triggers off the export of the 3+

**Comment by ollybh** [comment]
Here's the backtrace from the server error:
```
Caught exception #<ArgumentError: unknown keyword: :closed_when_used_up
/18xx/lib/engine/ability/choose_ability.rb:10:in `setup'
/18xx/lib/engine/ability/base.rb:36:in `initialize'
/18xx/lib/engine/game/g_18_royal_gorge/game.rb:384:in `new'
/18xx/lib/engine/game/g_18_royal_gorge/game.rb:384:in `event_treaty_of_boston!'
/18xx/lib/engine/phase.rb:26:in `block in buying_train!'
/18xx/lib/engine/phase.rb:25:in `each'
/18xx/lib/engine/phase.rb:25:in `buying_train!'
/18xx/lib/engine/depot.rb:25:in `export!'
/18xx/lib/engine/game/g_18_royal_gorge/game.rb:556:in `or_set_finished'
/18xx/lib/engine/game/g_18_royal_gorge/game.rb:477:in `next_round!'
/18xx/lib/engine/game/base.rb:848:in `transition_to_next_round!'
/18xx/lib/engine/game/base.rb:831:in `process_single_action'
/18xx/lib/engine/game/base.rb:778:in `process_action'
/18xx/routes/game.rb:103:in `block (6 levels) in <class:Api>'
/usr/local/bundle/gems/sequel-pg_advisory_lock-0.1.2/lib/sequel/extensions/pg_advisory_lock.rb:51:in `block in with_advisory_lock'
/usr/local/bundle/gems/sequel-5.55.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/local/bundle/gems/sequel-5.55.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/usr/local/bundle/gems/sequel-pg_advisory_lock-0.1.2/lib/sequel/extensions/pg_advisory_lock.rb:48:in `with_advisory_lock'
/18xx/routes/game.rb:55:in `block (5 levels) in <class:Api>'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:140:in `block in _is1'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:497:in `always'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:140:in `_is1'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:25:in `is'
/18xx/routes/game.rb:50:in `block (4 levels) in <class:Api>',
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:497:in `always'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:124:in `_verb'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:243:in `post'
/18xx/routes/game.rb:18:in `block (3 levels) in <class:Api>'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:57:in `block in on'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:497:in `always',
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_optimized_matching.rb:57:in `on'
/18xx/routes/game.rb:7:in `block (2 levels) in <class:Api>'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/hash_routes.rb:438:in `block in hash_branches'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:497:in `always'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/hash_routes.rb:438:in `hash_branches'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/hash_routes.rb:460:in `hash_routes'
/18xx/api.rb:82:in `block (2 levels) in <class:Api>'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/hash_routes.rb:438:in `block in hash_branches'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/request.rb:497:in `always'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/hash_routes.rb:438:in `hash_branches'
/18xx/api.rb:101:in `block in <class:Api>'
/usr/local/bundle/gems/roda-3.55.0/lib/roda.rb:518:in `_roda_run_main_route',
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/_before_hook.rb:27:in `_roda_run_main_route'
/usr/local/bundle/gems/roda-3.55.0/lib/roda.rb:496:in `block in _roda_handle_main_route'
/usr/local/bundle/gems/roda-3.55.0/lib/roda.rb:494:in `catch'
/usr/local/bundle/gems/roda-3.55.0/lib/roda.rb:494:in `_roda_handle_main_route'
/usr/local/bundle/gems/roda-3.55.0/lib/roda/plugins/error_handler.rb:88:in `_roda_handle_main_route'
/usr/local/bundle/gems/roda-3.55.0/lib/roda.rb:380:in `block in base_rack_app_callable'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/deflater.rb:47:in `call'
/usr/local/bundle/gems/message_bus-4.2.0/lib/message_bus/rack/middleware.rb:60:in `call'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/tempfile_reaper.rb:20:in `call'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/lint.rb:63:in `response'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/lint.rb:35:in `call'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/show_exceptions.rb:27:in `call',
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/common_logger.rb:43:in `call'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/chunked.rb:102:in `call'
/usr/local/bundle/gems/rack-3.0.9.1/lib/rack/content_length.rb:20:in `call'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:634:in `process_client'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:739:in `worker_loop'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:143:in `start'
/usr/local/bundle/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
/usr/local/bundle/bin/unicorn:25:in `load'
/usr/local/bundle/bin/unicorn:25:in `<main>'
```

**Comment by tphon** [comment]
Gmes https://18xx.games/game/161776 is still in error. At current state, clear all routes and select Auto. The error the occurs when submit £170 is selected.

**Comment by dfannius** [comment]
The fix has been made but has not been deployed yet. You will see the fix when it is.

**Comment by benjaminxscott** [comment]
fix is deployed if you'd like to try continuing

**Comment by BellmakerSA** [comment]
On Tuesday, May 7, 2024 at 12:43:52 AM EDT, Benjamin Scott ***@***.***> wrote:  
 
 


fix is deployed if you'd like to try continuing
