### ISSUE TITLE
docker-compose up is broken on master (c4f3d6d)

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#115]
With c4f3d6d checked out, this is the bottom of the output for the `rack` service:

```
rack_1     | ! Unable to load application: NoMethodError: undefined method `split' for nil:NilClass
rack_1     | /usr/local/lib/ruby/2.7.0/cgi/core.rb:384:in `parse': undefined method `split' for nil:NilClass (NoMethodError)
rack_1     | 	from /18xx/api.rb:18:in `<top (required)>'
rack_1     | 	from config.ru:10:in `require_relative'
rack_1     | 	from config.ru:10:in `block in <main>'
rack_1     | 	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
rack_1     | 	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
rack_1     | 	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
rack_1     | 	from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/single.rb:98:in `run'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
rack_1     | 	from /usr/local/bundle/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
rack_1     | 	from /usr/local/bundle/bin/puma:23:in `load'
rack_1     | 	from /usr/local/bundle/bin/puma:23:in `<main>'
rack_1     | 01:38:09 [rerun] Rerun (8) running 18xx (12)
```

Based on that output, this seems to be the broken line - https://github.com/tobymao/18xx/blob/c4f3d6dce05de2484156fbc6501a56e1ff8d2e75/api.rb#L18

I'm digging into it, but will keep an eye here in case someone beats me to it....

**Comment by michaeljb** [comment]
With this line:

```
puts "URI.parse(DB.uri).query.nil? = #{URI.parse(DB.uri).query.nil?}"
```

placed right above the `MessageBus.configure` line, this shows up in the output:

```
 URI.parse(DB.uri).query.nil? = true
```

So this:

```
    user: CGI.parse(URI.parse(DB.uri).query)['user'][0],
```

is basically being run as this:

```
    user: CGI.parse(nil)['user'][0],
```

and that's making `CGI` barf. I reproduced the `CGI` error message in an `irb` session:

```
> bundle exec rake irb
irb -I lib/ -I assets/js/
2.7.0 :001 > require 'cgi'
 => true 
2.7.0 :002 > CGI.parse(nil)
Traceback (most recent call last):
        5: from /home/michael/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
        4: from /home/michael/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
        3: from /home/michael/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        2: from (irb):2
        1: from /home/michael/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/cgi/core.rb:384:in `parse'
NoMethodError (undefined method `split' for nil:NilClass)
```

**Comment by michaeljb** [comment]
I don't know what to do next to solve this; my `DB.uri` looks as I'd expect:

```
DB.uri = postgres://root:password@db:5432/db_18xx
```

**Comment by michaeljb** [comment]
```
irb(main):003:0> uri = 'postgres://root:password@db:5432/db_18xx'
irb(main):004:0> 
irb(main):005:0> 
irb(main):006:0> URI.parse(uri)
=> #<URI::Generic postgres://root:password@db:5432/db_18xx>
irb(main):007:0> URI.parse(uri).query
=> nil
```

**Comment by michaeljb** [comment]
Getting closer I think

```
irb(main):009:0> URI.parse('postgres://root:password@db:5432/db_18xx?user=foo').query
=> "user=foo"
```

**Comment by michaeljb** [comment]
Changing the problem line to:

```
user: CGI.parse(URI.parse(DB.uri).query || '')['user'][0],
```

gets past the error above, but puts this repeatedly in the console:

```
rack_1     | W, [2020-04-21T02:07:06.898338 #14]  WARN -- : could not connect to server: No such file or directory
rack_1     | 	Is the server running locally and accepting
rack_1     | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
rack_1     |  subscribe failed, reconnecting in 1 second. Call stack
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus/backends/postgres.rb:203:in `initialize'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus/backends/postgres.rb:203:in `new'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus/backends/postgres.rb:203:in `raw_pg_connection'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus/backends/postgres.rb:136:in `subscribe'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus/backends/postgres.rb:349:in `global_subscribe'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus.rb:721:in `global_subscribe_thread'
rack_1     | /usr/local/bundle/gems/message_bus-2.2.4/lib/message_bus.rb:669:in `block in new_subscriber_thread'

```
