### ISSUE TITLE
GameError: Route is not connected in 1846

### ISSUE THREAD

**Issue by jsnell** [tobymao/18xx#1798]
The 1846 game https://www.18xx.games/game/11254 is only showing a blank page, with an uncaught exception in the Javascript console. The last action taken was using Lake Shore Lines to upgrade a city after the trains had already been routed.

The stack trace for the exception is:

```
GameError: Route is not connected
    at a.$game_error (https://www.18xx.games/assets/main.js:148:16558)
    at a.$check_connected! (https://www.18xx.games/assets/main.js:122:27299)
    at a.$revenue (https://www.18xx.games/assets/main.js:122:29499)
    at n (https://www.18xx.games/assets/main.js:4:8565)
    at Object.I.yieldX (https://www.18xx.games/assets/main.js:1:13543)
    at t (https://www.18xx.games/assets/main.js:5:2246)
    at Object.I.yield1 (https://www.18xx.games/assets/main.js:1:13260)
    at Array.$each (https://www.18xx.games/assets/main.js:5:31097)
    at I.send (https://www.18xx.games/assets/main.js:1:15202)
    at Array.$sum (https://www.18xx.games/assets/main.js:5:2133)
```

**Comment by tobymao** [comment]
this is due to you using lake shore line right after running routes and before paying dividends

when you run the routes, the paths are stored. but then you upgrade a city which causes the objects to be invalidated. this was fixed by caching the original city, so any action affecting the route after selecting it and before paying dividends will not have any effect

**Comment by tobymao** [comment]
i've deleted your LSL upgrade. you're on a pinned version of the game now. if you try LSL again before dividends, it will crash again

**Comment by roseundy** [comment]
If you really want the LSL power for your routes, you can undo to just after the normal tile lay and buy/use LSL.

**Comment by jsnell** [comment]
The game is still in a state where loading it results in the same Javascript exception, though at least it's no longer a blank page.

Undoing results in a HTTP 400 with a response of {"error":"Game out of sync"}, any other action seems to have no effect. (I didn't dare to try redoing)

**Comment by roseundy** [comment]
The json for this seems fishy.

**Comment by tobymao** [comment]
i've deleted a couple more actions no more error
