### ISSUE TITLE
Error when placing a tile

### ISSUE THREAD

**Issue by McDood** [tobymao/18xx#18]
Happened a few time to me, I'm not sure of the exact trigger. 
I select a map tile to view the available tiles, 
I select one, rotate a few times, cancel, 
select another, rotate a few times, cancel
repeat
when selecting the tile after, nothing happens and there is an error in the console
Once this happens, I cannot cancel, or apply. every click on the map seems to register an error in the console. I can resolve the issue with the undo button

**Console output**
"owner: undefined method `owner' for #<Engine::Train::Depot:0x4840>
    at constructor.$method_missing (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:3907:56)
    at constructor.method_missing_stub (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:1310:35)
    at $$2 (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:39807:17)
    at Object.Opal.yield1 (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:1449:20)
    at $$94 (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:10218:22)
    at Object.Opal.yieldX (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:1472:20)
    at self.$each.$$p (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:8748:26)
    at Object.Opal.yield1 (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:1452:14)
    at constructor.$each (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:14806:14)
    at constructor.$collect (http://159.203.254.109:9292/assets/app.6120dd8da45b9ed7eff1564b0786d20abd9ec95fac096101105734ad1f982b8f.js:8753:12)"

**Comment by tobymao** [comment]
i can't reproduce this one anymore, if you can recreate this on the live website i can easily repro
