### ISSUE TITLE
[1817] Unable to purchase station markers during stock round

### ISSUE THREAD

**Issue by ggohierroy** [tobymao/18xx#1853]
Hotseat game where the current state is problematic:
https://18xx.games/hotseat/hs_tazjuqsy_1602556628

Link to data gist:
https://gist.github.com/ggohierroy/4bbd2172283d6c99922c0d2a57e7747a

During SR5, each player started a new company 5-share company
When clicking on the Buy Tokens button, nothing happens

**Comment by roseundy** [comment]
Stack trace:
"BuyTokens: uninitialized constant Engine::Action::BuyTokens
    at Function.$const_missing (http://localhost:9292/assets/opal.js:3052:52)
    at const_missing (http://localhost:9292/assets/opal.js:224:32)
    at Opal.const_get_qualified (http://localhost:9292/assets/opal.js:271:38)
    at Object.$$11 (http://localhost:9292/assets/app.js:8355:41)
    at invokeHandler (http://localhost:9292/assets/deps.js:1880:17)
    at handleEvent (http://localhost:9292/assets/deps.js:1908:9)
    at HTMLButtonElement.handler (http://localhost:9292/assets/deps.js:1913:9)"

Looks like BuyTokens isn't defined anywhere.

**Comment by jenf** [comment]
Forgot to git add a file :( fixed in 498980a
