### ISSUE TITLE
18MEX: Game hung - undefined method highlight for nil

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2217]
https://18xx.games/game/14991
Some GUI bug?

This is how it looks like
a
args: []
message: "undefined method `highlight?' for nil"
name: "highlight?"
stack: "highlight?: undefined method `highlight?' for nil↵    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)↵    at a.n (https://18xx.games/assets/main.js:1:11652)↵    at a.$render_shares (https://18xx.games/assets/main.js:118:16219)↵    at a.$render (https://18xx.games/assets/main.js:118:8867)↵    at a.$h (https://18xx.games/assets/main.js:68:13843)↵    at e (https://18xx.games/assets/main.js:117:15931)↵    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13260)↵    at Array.$collect (https://18xx.games/assets/main.js:5:27210)↵    at Object.I.send (https://18xx.games/assets/main.js:1:15202)↵    at Array.$map (https://18xx.games/assets/main.js:1:17338)"
__proto__: a

When changing to https://18xx.games/game/14991?debug=1
the game appeared again? 
So is it browser related?

**Comment by perwestling** [comment]
The highlight issue was fixed for another issue, so I close this issue.
