### ISSUE TITLE
[1817] can not pass loans after merger if both corps have token in same city

### ISSUE THREAD

**Issue by Rubenvanheck** [tobymao/18xx#2283]
Game: https://18xx.games/game/14687?action=378

After merging two 2-share companies (both with their token in Cleveland) the "Pass (Loans)" button in the post-merger process does not work. If I press it, the other buttons and the chat also no longer work until refreshing the page.

**Comment by jenf** [comment]
Very likely it's related to the two tokens

```a
args: [1]
message: "undefined method `+' for nil"
name: "+"
stack: "+: undefined method `+' for nil↵    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)↵    at a.n (https://18xx.games/assets/main.js:1:11652)↵    at t (https://18xx.games/assets/main.js:75:4691)↵    at a.$active_entities (https://18xx.games/assets/main.js:75:9173)↵    at a.$current_entity (https://18xx.games/assets/main.js:80:24569)↵    at a.$current_actions (https://18xx.games/assets/main.js:80:24390)↵    at a.$blocking? (https://18xx.games/assets/main.js:80:24868)↵    at r (https://18xx.games/assets/main.js:102:3287)↵    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13260)↵    at t (https://18xx.games/assets/main.js:4:19095)"
__proto__: a``

**Comment by jenf** [comment]
also a dup of #2281
