### ISSUE TITLE
[1817] - undefined method `can_merge?'

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2939]
Link: https://18xx.games/game/20758

Player started bidding on a new company, but was unable to place its home station. When we reloaded the page, the console shows:
```
Uncaught 
a
args: Array(2)
0: a {$$id: 6740, id: 4227, name: "gatesman", cash: 2, companies: Array(0), …}
1: a {$$id: 7458, name: "SR", id: "SR", full_name: "Strasburg Railroad", shares_by_corporation: a, …}
length: 2
__proto__: t(0)
message: "undefined method `can_merge?' for #<Engine::Step::G1817::BuySellParShares:0x14e14>"
name: "can_merge?"
stack: "can_merge?: undefined method `can_merge?' for #<Engine::Step::G1817::BuySellParShares:0x14e14>↵    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)↵    at a.n (https://18xx.games/assets/main.js:1:11652)↵    at a.$render_merge (https://18xx.games/assets/main.js:134:19904)↵    at a.$render (https://18xx.games/assets/main.js:134:13934)↵    at a.$h (https://18xx.games/assets/main.js:68:13843)↵    at a.$render_input (https://18xx.games/assets/main.js:142:32653)↵    at e (https://18xx.games/assets/main.js:142:32356)↵    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13260)↵    at Array.$collect (https://18xx.games/assets/main.js:5:27210)↵    at Object.I.send (https://18xx.games/assets/main.js:1:15202)"
__proto__: a
```

My one guess is the player was trying to set the new railroad's home to the same as the home of one of their other railroads.

**Comment by ventusignis** [comment]
https://github.com/tobymao/18xx/pull/2849/commits/883d79ce4e2efdb0870e8cc4fbf7dcd2485aa95d
This commit breaks 1817 games when parring corporations in the SR when there is a share choice; the SellBuySell shares action has 'choose' as an action, but does not implement `can_merge`
