### ISSUE TITLE
[1849] Game cannot load

### ISSUE THREAD

**Issue by Zwergenpunk** [tobymao/18xx#3681]
The 1849 game is broken and cannot load 

https://18xx.games/game/24705

The exception is 

```
"can_buy?: undefined method `can_buy?' for <Engine::Step::G1849::IssueShares>
    at a.$method_missing (https://18xx.games/assets/main.js:2:20031)
    at a.n (https://18xx.games/assets/main.js:1:11652)
    at e (https://18xx.games/assets/main.js:158:28712)
    at Object.I.yield1 (https://18xx.games/assets/main.js:1:13260)
    at Array.$collect (https://18xx.games/assets/main.js:5:27210)
    at Object.I.send (https://18xx.games/assets/main.js:1:15202)
    at Array.$map (https://18xx.games/assets/main.js:1:17338)
    at I.send (https://18xx.games/assets/main.js:1:15202)
    at a.$render_ipo_shares (https://18xx.games/assets/main.js:158:28479)
    at a.$render_buy_shares (https://18xx.games/assets/main.js:158:27538)"
```

**Comment by Zwergenpunk** [comment]
This is the same as in #3682
