### ISSUE TITLE
[1849] Can't submit routes

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#4574]
https://18xx.games/game/33103

Uncaught 
y
args: []
message: "undefined method `paths' for {"nodes"=>[<Engine::Part::Town: hex: G1>, <Engine::Part::City: hex: E1>], "paths"=>[<Path: hex: G1, exit: 3, track: broad>, <Path: hex: E1, exit: 0, track: dual>], "hexes"=>[<Engine::Hex: G1, tile: 58>, <Engine::Hex: E1, tile: E1>], "id"=>["G1", "E1"]}"
name: "paths"
stack: "paths: undefined method `paths' for {"nodes"=>[<Engine::Part::Town: hex: G1>, <Engine::Part::City: hex: E1>], "paths"=>[<Path: hex: G1, exit: 3, track: broad>, <Path: hex: E1, exit: 0, track: dual>], "hexes"=>[<Engine::Hex: G1, tile: 58>, <Engine::Hex: E1, tile: E1>], "id"=>["G1", "E1"]}↵    at y.$method_missing (https://18xx.games/assets/deps.js:4:12551)↵    at y.d (https://18xx.games/assets/deps.js:1:11736)↵    at y.$hex_edge_cost (https://18xx.games/assets/g_1849.js:4:6721)↵    at n (https://18xx.games/assets/g_1849.js:4:7131)↵    at Object.n.yieldX (https://18xx.games/assets/deps.js:1:13656)↵    at https://18xx.games/assets/deps.js:8:45283↵    at ke (https://18xx.games/assets/deps.js:8:45332)↵    at Object.n.yield1 (https://18xx.games/assets/deps.js:1:13373)↵    at Array.$each (https://18xx.games/assets/deps.js:8:76164)↵    at n.send (https://18xx.games/assets/deps.js:1:15319)"
__proto__: y

**Comment by jenf** [comment]
@roseundy
